### ISSUE TITLE
Invoking `!players` causes NullPointerException

### ISSUE THREAD

**Issue by CRTified** [overflowerror/minecraft-matrix-bridge#3]
The command introduced by #1 causes a NullPointerException on papermc-1.18.1#132:
```
Jan 04 14:10:20 cloudbox minecraft-server[524608]: [14:10:20 WARN]: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsString()" because the return value of "com.google.gson.JsonObject.get(String)" is null
Jan 04 14:10:20 cloudbox minecraft-server[524608]: [14:10:20 WARN]:         at matrixbridge-1.0-SNAPSHOT-jar-with-dependencies.jar//io.kamax.matrix.json.event.MatrixJsonRoomMessageEvent.getBody(MatrixJsonRoomMessageEvent.java:42)
Jan 04 14:10:20 cloudbox minecraft-server[524608]: [14:10:20 WARN]:         at matrixbridge-1.0-SNAPSHOT-jar-with-dependencies.jar//at.overflow.bukkit.matrixbridge.BridgeService.run(BridgeService.java:76)
```

**Comment by CRTified** [comment]
Nevermind, it seems like something went wrong on my side.

**Comment by CRTified** [comment]
Okay, it might be caused by [this unimplemented function](https://github.com/overflowerror/minecraft-matrix-bridge/blob/master/src/main/java/at/overflow/bukkit/matrixbridge/BridgeService.java#L116), I guess?
